### PR TITLE
Add documentation for AD

### PR DESCRIPTION
**Pull request by VijayanB**
Create doc for AD plugin

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jmazanec15 — COMMENTED** [review]
Why have this information in this repo as opposed to https://github.com/opendistro/for-elasticsearch-docs which hosts https://opendistro.github.io/for-elasticsearch-docs/?

From my perspective, it seems like general information about the project and information for developers should be hosted in project repo and usage information should be hosted in docs repo. What are your thoughts @VijayanB  @aetter @vamshin?

**Comment by aetter** [comment]
Yeah that's exactly it @jmazanec15. Downloading and using something (including the API) in the docs, building and contributing in the repo. We have a PR ready to go for odfe-cli whenever it's out: https://github.com/opendistro/for-elasticsearch-docs/pull/368

**Comment by vamshin** [comment]
> Why have this information in this repo as opposed to https://github.com/opendistro/for-elasticsearch-docs which hosts https://opendistro.github.io/for-elasticsearch-docs/?
> 
> From my perspective, it seems like general information about the project and information for developers should be hosted in project repo and usage information should be hosted in docs repo. What are your thoughts @VijayanB @aetter @vamshin?

Makes sense. We could have this content in docs repo and probably point this link in the repo as well.

**Comment by VijayanB** [comment]
@aetter As far as i remember that in our last discussion we decided that we will not be able to cover every commands from every plugin on docs repo. We will have only basic commands like profile and usage. Hence, this doc is created here. We will be happy to move all our example usage to doc page if everyone agrees.

**Comment by aetter** [comment]
> @aetter As far as i remember that in our last discussion we decided that we will not be able to cover every commands from every plugin on docs repo. We will have only basic commands like profile and usage. Hence, this doc is created here. We will be happy to move all our example usage to doc page if everyone agrees.

Correct, yeah, I don't have any interest in having 15 pages in the CLI documentation with every single command when people can just do a list command from the command line.

**Comment by VijayanB** [comment]
Since this will be added in new documentation repo

**Pull request closed without merging**
