### PR TITLE
Enable shell auto completion.

### PR DESCRIPTION
**Pull request by VijayanB**
Added command to generate and auto complete script.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by VijayanB** [comment]
Will add documentation PR once we finalize whether we will be adding here or in doc repo.

**Comment by VijayanB** [comment]
Output
```
3c22fb3bf9b7:odfe-cli balasvij$ ./odfe-cli --help
odfe-cli is a unified command line interface for managing ODFE clusters

Usage:
  odfe-cli [command]

Available Commands:
  ad          Manage the Anomaly Detection plugin
  completion  Generate completion script for your shell
  help        Help about any command
  profile     Manage a collection of settings and credentials that you can apply to an odfe-cli command

Flags:
  -c, --config string    Configuration file for odfe-cli, default is /Users/balasvij/.odfe-cli/config.yaml
  -h, --help             Help for odfe-cli
  -p, --profile string   Use a specific profile from your configuration file
  -v, --version          Version for odfe-cli

Use "odfe-cli [command] --help" for more information about a command.


```

```
3c22fb3bf9b7:odfe-cli balasvij$ ./odfe-cli completion --help
To enable shell autocompletion:

Bash:

$ source <(odfe-cli completion bash)

# To enable auto command completions for each session, execute once:
Linux:
  $ odfe-cli completion bash > /etc/bash_completion.d/odfe-cli
MacOS:
  $ odfe-cli completion bash > /usr/local/etc/bash_completion.d/odfe-cli

Zsh:

# If shell completion is not already enabled in your environment you will need
# to enable it.  You can execute the following once:

$ echo "autoload -U compinit; compinit" >> ~/.zshrc

# To enable auto command completions for each session, execute once:
$ odfe-cli completion zsh > "${fpath[1]}/_odfe-cli"

# You will need to start a new shell for this setup to take effect.

Fish:

$ odfe-cli completion fish | source

# To enable auto command completions for each session, execute once:
$ odfe-cli completion fish > ~/.config/fish/completions/odfe-cli.fish

Powershell:

PS> odfe-cli completion powershell | Out-String | Invoke-Expression

# To enable auto command completions for each session, execute once:
PS> odfe-cli completion powershell > odfe-cli.ps1
# and source this file from your powershell profile.

Usage:
  odfe-cli completion [ bash | zsh | fish | powershell ]

Flags:
  -h, --help   help for completion

Global Flags:
  -c, --config string    Configuration file for odfe-cli, default is /Users/balasvij/.odfe-cli/config.yaml
  -p, --profile string   Use a specific profile from your configuration file
3c22fb3bf9b7:odfe-cli balasvij$ 

```

**Review by jmazanec15 — COMMENTED** [review]
I like auto-complete better than completion. Why did you go with completion?

**Comment by VijayanB** [comment]
> I like auto-complete better than completion. Why did you go with completion?

i updated since auto-complete seems long and [kubernetes](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#completion)  also uses completion as command.

**Comment by jmazanec15** [comment]
Makes sense

**Review by jmazanec15 — APPROVED** [review]

**Pull request merged**
